Repository jenkinsci/pipeline-model-definition-plugin, pull requests merged in 2021-11, with the labels that each got.

#462 Assume that configured agents are online
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
Labels: tests

#465 Set `child.scm.*.inherit.append.path=false`
  pom.xml
Labels: maintenance

#459 Bump `json-schema-validator` from 2.0.4 to 2.2.14
  pipeline-model-api/pom.xml
  pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ASTSchema.java
  pipeline-model-definition/pom.xml
  pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy
  pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy
  pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy
  pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONErrorCollector.groovy
  pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BaseParserLoaderTest.java
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineActionTest.java
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONSchemaTest.java
  pipeline-model-extensions/pom.xml
  pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/CommonUtils.java
  pipeline-stage-tags-metadata/pom.xml
  pom.xml
Labels: dependencies
