Repository jenkinsci/pipeline-model-definition-plugin, pull requests merged in 2022-03, with the labels that each got.

#498 Update plugin parent POM and plugin BOM
  pipeline-model-definition/pom.xml
  pom.xml
Labels: maintenance

#501 Revert "Update plugin parent POM and plugin BOM"
  pipeline-model-definition/pom.xml
  pom.xml
Labels: dependencies

#503 Update parent POM
  pipeline-model-definition/pom.xml
  pom.xml
Labels: dependencies

#502 Update plugin BOM and jenkins version
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/LibrariesTest.java
  pom.xml
Labels: dependencies

#506 core.longpaths config no longer needed for windows git
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/LibrariesTest.java
Labels: tests
