Repository jenkinsci/pipeline-model-definition-plugin, pull requests merged in 2022-01, with the labels that each got.

#477 Skip resource-intensive tests on CI
  pom.xml
Labels: tests

#473 EOL JSR 305
  pipeline-model-api/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DescriptorLookupCacheTest.java
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTester.java
Labels: dependencies

#479 The JVM used by maven is unconfigured and uses default ergonomics
  .mvn/jvm.config
Labels: tests

#480 optimize memory usage to remove test failures
  .mvn/jvm.config
  pom.xml
Labels: tests

#484 enable cd
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pipeline-model-api/pom.xml
  pipeline-model-definition/pom.xml
  pipeline-model-extensions/pom.xml
  pipeline-stage-tags-metadata/pom.xml
  pom.xml
Labels: internal

#485 fix indentation in dependabot.yml
  .github/dependabot.yml
Labels: internal

#488 update README
  README.md
Labels: documentation
