Repository jenkinsci/pipeline-model-definition-plugin, pull requests merged in 2024-01, with the labels that each got.

#682 [JENKINS-70695] add copy to clipboard button for declarative generator
  pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/index.jelly
  pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/indexScript.js
Labels: enhancement

#681 Require Jenkins 2.426.1 instead of 2.426
  pom.xml
Labels: dependencies

#660 Allow valid agent types in PCT context
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ErrorsEndpointOpsTest.java
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ErrorsJSONParserTest.java
Labels: developer

#672 Remove unnecessary test method
  pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java
Labels: tests

#684 Use joda-time api plugin
  pipeline-model-api/pom.xml
Labels: enhancement

#570 Refresh sidebar icon
  pipeline-model-definition/pom.xml
  pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineAction.java
  pipeline-model-definition/src/main/webapp/images/24x24/restart-stage.png
  pipeline-model-definition/src/main/webapp/images/48x48/restart-stage.png
Labels: enhancement
